name: labs - test & lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.13.0"
          rebar3-version: "3"
          # elixir-version: "1"
      - run: gleam deps download
        working-directory: lab1
      - run: gleam test
        working-directory: lab1
      - run: gleam format --check src test
        working-directory: lab1

      - run: gleam deps download
        working-directory: lab2
      - run: gleam test
        working-directory: lab2
      - run: gleam format --check src test
        working-directory: lab2
